# This rule is not used by the project elastic-rules itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over elasticdetectionrules.gopes0x00.internal.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elastic-rules
    app.kubernetes.io/managed-by: kustomize
  name: elasticdetectionrule-admin-role
rules:
- apiGroups:
  - elasticdetectionrules.gopes0x00.internal
  resources:
  - elasticdetectionrules
  verbs:
  - '*'
- apiGroups:
  - elasticdetectionrules.gopes0x00.internal
  resources:
  - elasticdetectionrules/status
  verbs:
  - get
